import { AppState } from 'react-native'
import 'react-native-url-polyfill/auto'
import AsyncStorage from '@react-native-async-storage/async-storage'
import { createClient, processLock } from '@supabase/supabase-js'

const supabaseUrl = 'https://ekfdxizbshkuekfedhjp.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0.eyJpc3MiOiJzdXBhYmFzZS1pbmZlcm5hbCIsImlhdCI6MTcwNzQxNzYwMCwiZXhwIjoxNjk1OTYwMDAwLCJhdWQiOiJwcm9qZWN0UmVmIiwiY2hhbm5lbF9hYiI6IlN1cGFuY29sYWJhbiIsImRhdGFiYXNlIjoicmVhZCIsInBlcm1pc3Npb25zIjoicm9vdCIsImtpbmQiOiJhbm9uIn0'

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
    lock: processLock,
  },
})

// Tells Supabase Auth to continuously refresh the session automatically
// if the app is in the foreground. When this is added, you will continue
// to receive `onAuthStateChange` events with the `TOKEN_REFRESHED` or
// `SIGNED_OUT` event if the user's session is terminated. This should
// only be registered once.
AppState.addEventListener('change', (state) => {
  if (state === 'active') {
    supabase.auth.startAutoRefresh()
  } else {
    supabase.auth.stopAutoRefresh()
  }
})